"""Regenerate `game/src/ap_voice_lines.inc` from the install's voice VPK.

The NPC Trap's characters say lines they have in the game. This lists every
voice file of each character, by filename prefix, so the DLL can pick a few
per map to precache. Rerun only if the character table below changes.

Usage:
    python tools/gen_voice_lines.py [--game "<Half-Life 2 folder>"]
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "game" / "src" / "ap_voice_lines.inc"
VPK = Path("hl2") / "hl2_sound_vo_english_dir.vpk"

# Character (index order matches kStoryModels in ap_traps.cpp) and the voice
# file prefixes under sound/ that are theirs.
CHARACTERS: list[tuple[str, list[str]]] = [
    ("gman", ["vo/gman_misc/", "vo/citadel/gman_"]),
    ("kleiner", ["vo/k_lab/kl_", "vo/k_lab2/kl_", "vo/novaprospekt/kl_"]),
    ("eli", ["vo/eli_lab/eli_", "vo/citadel/eli_"]),
    ("breen", ["vo/breencast/br_", "vo/citadel/br_"]),
    ("mossman", ["vo/eli_lab/mo_", "vo/citadel/mo_"]),
    ("alyx", ["vo/eli_lab/al_", "vo/k_lab/al_", "vo/novaprospekt/al_", "vo/citadel/al_",
              "vo/npc/alyx/"]),
    ("barney", ["vo/k_lab/ba_", "vo/trainyard/ba_", "vo/npc/barney/"]),
    ("monk", ["vo/ravenholm/monk_"]),
    ("odessa", ["vo/coast/odessa/nlo_"]),
]


def vpk_files(path: Path) -> list[str]:
    files = []
    with path.open("rb") as f:
        _sig, version, _tree = struct.unpack("<III", f.read(12))
        if version == 2:
            f.read(16)

        def string() -> str:
            out = bytearray()
            while (c := f.read(1)) != b"\0":
                out += c
            return out.decode("latin-1")

        while ext := string():
            while folder := string():
                while name := string():
                    f.read(4)
                    preload, = struct.unpack("<H", f.read(2))
                    f.read(12 + preload)
                    files.append(f"{folder}/{name}.{ext}".lower())
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--game", type=Path, help="the Half-Life 2 install folder")
    args = parser.parse_args(argv)
    game = args.game
    if game is None:
        sys.path.insert(0, str(REPO / "apworld" / "half_life_2"))
        import mod
        game = mod.hl2_install_dir()
    if game is None or not (game / VPK).is_file():
        print("Half-Life 2 install not found; pass --game", file=sys.stderr)
        return 2
    wavs = sorted(f[len("sound/"):] for f in vpk_files(game / VPK)
                  if f.startswith("sound/") and f.endswith(".wav"))
    lines = ["// Generated by tools/gen_voice_lines.py from the retail voice VPK. Do not edit.",
             "// One block per NPC Trap character, in kStoryModels order."]
    for name, prefixes in CHARACTERS:
        own = [w for w in wavs if any(w.startswith(p) for p in prefixes)]
        if not own:
            print(f"no lines for {name}", file=sys.stderr)
            return 1
        lines.append(f"static const char* const kLines_{name}[] = {{")
        lines += [f'    "{w}",' for w in own]
        lines.append("};")
    lines.append("static const VoiceLines kVoiceLines[] = {")
    lines += [f"    {{kLines_{name}, ARRAYSIZE(kLines_{name})}}," for name, _ in CHARACTERS]
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(REPO)}: " +
          ", ".join(f"{name} {sum(1 for w in wavs if any(w.startswith(p) for p in ps))}"
                    for name, ps in CHARACTERS))
    return 0


if __name__ == "__main__":
    sys.exit(main())
