"""Emit the game's data file, `checkdata.txt`, from `campaign.json`.

The server dll reads a line-oriented, pipe-delimited format rather than JSON:
every record is one split, and the dll needs no JSON parser. Generating it from
the same JSON the apworld reads is what keeps ids from drifting between the two
halves.

Usage:
    python tools/gen_checkdata.py [--check]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CAMPAIGN_PATH = REPO_ROOT / "apworld" / "half_life_2" / "data" / "campaign.json"
# Bundled in the world package so a zipped .apworld can install the mod folder
# itself. It lands in `hl2ap/archipelago/`, next to the bridge files.
OUT_PATH = (REPO_ROOT / "apworld" / "half_life_2" / "mod" / "files"
            / "archipelago" / "checkdata.txt")

# 1: first format.
FORMAT_VERSION = 1

HEADER = """\
# Generated by tools/gen_checkdata.py; do not edit by hand.
# Record types:
#   V|<format version>
#   D|<data version>                 must match the client's, or ids differ
#   B|<hub map>                      where runs start and chapters return to
#   N|<campaign>|<short>|<name>|<goal chapter>
#   C|<index>|<key>|<number>|<name>|<map,map,...>|<is_goal>|<campaign>|<complete on>|<exits>
#     <complete on> is forward_exit or finale; <exits> is from>to,... (the
#     changelevels into the next chapter)
#   L|<id>|<map>|<type>|<arg>|<name>[|<x y z>]
#     <arg>: weapon_pickup/item_pickup/weapon_upgrade classnames,...; charger
#     <classname>@<x y z>; chapter_complete the chapter key; map_reached empty.
#     weapon_upgrade is holding the upgraded form (the super gravity gun)
#   F|<location id>|<map>|<x y z>|<how>|<spawner>|<confirmed>   one way to a pickup
#     check: a chapter's
#     first copy. <how> is placed, crate, drop, ally, give or upgrade (a
#     trigger that upgrades a held weapon); <x y z> is empty for a give with
#     no place. <spawner> is `<targetname>,<input>` for a copy that only exists
#     once that entity gets that input (a template), else empty. <confirmed>
#     is 1 for a copy confirmed reachable in play that the maps cannot prove
#   K|<classname>|<item name>        a pickup refused until the item arrives
#   P|<item name>|<stages>|<classname>   a progressive item and its stage count
#                                          (classname empty for a non-weapon)
#   H|<chapter key>|<vehiclescript>|<item name>   the key a chapter's vehicle needs
#   U|<item name>|<map,map,...>      a vehicle upgrade and the maps that enable it
#   X|<map>|<targetname,...>         a cold-load kit's pickups: never checks
# A charger's position is its rounded origin. The game matches the unit a
# player used by nearest same-class entity within a radius, never by rounding.
"""


def render(data: dict) -> str:
    lines = [HEADER.rstrip("\n"), f"V|{FORMAT_VERSION}", f"D|{data['data_version']}",
             f"B|{data['hub_map']}"]
    for campaign in data["campaigns"]:
        lines.append("N|{key}|{short}|{name}|{goal_chapter}".format(**campaign))
    for index, chapter in enumerate(data["chapters"]):
        lines.append("C|{i}|{key}|{number}|{name}|{maps}|{goal}|{campaign}|{on}|{exits}".format(
            i=index, key=chapter["key"], number=chapter["number"], name=chapter["name"],
            maps=",".join(chapter["maps"]), goal=int(chapter["is_goal"]),
            campaign=chapter["campaign"],
            on="finale" if chapter["is_goal"] else "forward_exit",
            exits=",".join(f"{a}>{b}" for a, b in chapter["exits"])))
    for chapter in data["chapters"]:
        for map_name, names in chapter.get("kits", {}).items():
            lines.append(f"X|{map_name}|{','.join(names)}")
    for location in data["locations"]:
        trigger = location["trigger"]
        kind = trigger["type"]
        if kind in ("weapon_pickup", "item_pickup", "weapon_upgrade"):
            arg = ",".join(trigger["classnames"])
        elif kind == "charger":
            arg = f"{trigger['classname']}@{trigger['at']}"
        elif kind == "chapter_complete":
            arg = trigger["chapter"]
        else:
            arg = ""
        record = f"L|{location['id']}|{location['map']}|{kind}|{arg}|{location['name']}"
        if "position" in location:
            record += "|" + " ".join(str(v) for v in location["position"])
        lines.append(record)
        for source in location.get("sources", ()):
            how = "ally" if source.get("drop") == "ally" else source["how"]
            lines.append("F|{id}|{map}|{pos}|{how}|{spawner}|{confirmed}".format(
                id=location["id"], map=source["map"],
                pos=" ".join(str(v) for v in source.get("position", ())), how=how,
                spawner=source.get("spawner", ""),
                confirmed=1 if source.get("confirmed") else 0))
    for item in data["items"]:
        group = item["group"]
        # Every item that comes in copies, weapon or not (Progressive Aux Power
        # has no classname): the harness sends copy counts only for these.
        if "count" in item:
            classnames = item.get("classnames") or [""]
            lines.append(f"P|{item['name']}|{item['count']}|{classnames[0]}")
        if group in ("weapon", "equipment"):
            for classname in item["classnames"]:
                lines.append(f"K|{classname}|{item['name']}")
        elif group == "vehicle_key":
            lines.append(f"H|{item['chapter']}|{item['vehiclescript']}|{item['name']}")
        elif group == "vehicle_upgrade":
            lines.append(f"U|{item['name']}|{','.join(item['maps'])}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed file differs from a fresh render")
    args = parser.parse_args(argv)
    text = render(json.loads(CAMPAIGN_PATH.read_text(encoding="utf-8")))
    if args.check:
        if not OUT_PATH.exists() or OUT_PATH.read_text(encoding="utf-8") != text:
            print("checkdata.txt is out of date; run tools/gen_checkdata.py", file=sys.stderr)
            return 1
        print("checkdata.txt is current")
        return 0
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
